version: '3.7'

services:
    
    mongodb:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - /var/lib/mongodb:/var/lib/mongodb

    smtp4dev:
        image: opvolger/rnwoodsmtp4dev
        ports:
            - "3000:80"
            - "2525:25"